# Generated by Django 4.0.5 on 2022-06-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0002_alter_item_date_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('O', 'OFFER'), ('C', 'CATEGORY')], max_length=10),
        ),
    ]
