# Generated by Django 4.0.5 on 2022-06-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0004_alter_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.CharField(max_length=32),
        ),
    ]
