# Generated by Django 4.0.5 on 2022-06-20 03:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0005_alter_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_last_update',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
