# Generated by Django 4.0.5 on 2022-06-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0006_item_price_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_last_update',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
