# Generated by Django 4.0.5 on 2022-06-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0008_alter_item_price_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('OFFER', 'OFFER'), ('CATEGORY', 'CATEGORY')], max_length=10),
        ),
    ]
